name: docker-image-build

on:
#  workflow_run:
#    workflows:
#      - acceptance-test-analyze-with-sonarcloud
#    types:
#      - completed
  push:
    branches:
#      - 'release'
      - 'protoseo/base-#220' # TEST FOR DOCKER IMAGE BUILD

jobs:
  build:
    name: docker image build
    runs-on: ubuntu-latest
    steps:
      - name: branch
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build -x test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/asap:${{ github.head_ref }}
